### ISSUE TITLE
keen1

### ISSUE THREAD

**Issue by daurrutia** [theonemule/dos-game#6]
Hi thanks for developing this.

Question: What is `keen1` within your dockerfile? Is that a file that should be in the `keen/` dir?

**Comment by daurrutia** [comment]
I see it's a result of the game install. 

I think my container is missing the installation step. I'm using the dockerfile in the repo. How/where does the game install happen?

**Comment by theonemule** [comment]
That's the command to run the game. I don't think it's working right now. You can pretty much ignore it. :)

**Comment by daurrutia** [comment]
I got an error that that file doesn't exist, so the game fails to start automatically. 

I'm trying to pinpoint where the game install actually happens to automatically generate the keen1 command/file.
